# Use a Python base image. 'slim-buster' is a smaller, more secure Python image.
FROM python:3.9-slim-buster

# Set the working directory inside the container. All subsequent commands will run from here.
WORKDIR /app

# Copy requirements.txt into the container and install dependencies.
# We do this before copying other files to leverage Docker's build cache.
# If requirements.txt doesn't change, Docker won't re-run pip install.
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy  Python scripts and the trained model file into the container.
# The 'linear_regression_model.joblib' file is generated by train.py
# during the CI process, so it needs to be copied into the image.
COPY train.py .
COPY predict.py .
COPY linear_regression_model.joblib .

# Define the default command to run when the container starts without specific commands.
# This is useful for local testing or if you just want to run the prediction as a default.
CMD ["python", "predict.py"]